@startuml i9rfs_api_arch
!include <C4/C4_Component>

title Component Diagram for i9rfs API Server

' Container(api, "i9rfs API Server", "Node.js")

System_Ext(emailSystem, "Email System", "Google SMTP")
System(cloudStorageSystem, "Cloud Storage System", "Google Cloud Storage")

ContainerDb(database, "Database", "Neo4j")

Component(cloudStorageService, "Cloud Storage Service", "GCS Node.js client library", "Consists functions for GCS bucket management, converting object cloud names to download URLs, and getting upload URLs")
Rel(cloudStorageService, cloudStorageSystem, "Uses")

Component(securityServices, "Security Services", "Node.js, jsonwebtoken, bcrypt", "Consists security functions for JWT signing/verification, generating 6-digit token/code with expiration etc.")
Component(mailService, "Mail Service", "Node.js, nodemailer", "Consists a function for sending email to client")
Rel(mailService, emailSystem, "Uses")

Component(userService, "User Service", "Node.js", "Consists functions that provide required user services required by controllers such as signup and signin—for user existence check and account creation, upload service and RFS service—for user storage quota management")
Component(userModel, "User Model", "Neo4j, Cypher, neo4j-driver", "Consists functions that encapsulates user-related database logic and return resulting data to calling user services")
Rel(userService, userModel, "Calls")
Rel(userModel, database, "Reads/Writes")

Component(signupControllers, "Signup Controllers", "Node.js, Express", "Consists request handlers for the 3-step user signup process (new account request, email verification, and final user registration) and signup session management")
Component(signupService, "Signup Service", "Node.js", "Consists functions that provide required services to signup controllers; user existence checks, mailing verification code and setting code expiration, signup session data generation, password encryption, creating user account, auto-login user by signing a JWT token")
Rel(signupControllers, signupService, "Calls")
Rel(signupService, userService, "Calls")
Rel(signupService, securityServices, "Calls")
Rel(signupService, mailService, "Calls")

Component(signinControllers, "Signin Controllers", "Node.js, Express", "Consists request handler for user signin")
Component(signinService, "Signin Service", "Node.js", "Consists a function that provide the required service to the signin controller; user existence checks, password matching check, JWT token signing")
Rel(signinControllers, signinService, "Calls")
Rel(signinService, userService, "Calls")
Rel(signinService, securityServices, "Calls")

Component(uploadService, "Upload Service", "Node.js", "Consists a function for authorizing an upload and returning an upload URL")
Rel(uploadService, userService, "Calls")
Rel(uploadService, cloudStorageService, "Calls")

Component(appControllers, "App Controllers", "Node.js, Express", "Consists request handlers for upload authorization and user signout")
Rel(appControllers, uploadService, "Calls")

Component(rfsController, "Remote File System Controller", "Node.js, WebSocket", "Accepts a client's Web socket connection, authenticates the client, listens for WS messages (file system commands with associated data) on the connection, decodes a message, passes it to target handling services, and writes reply to the client connection")
Component(rfsService, "Remote File System Service", "Node.js", "Consists service funtions for all remote file system operations providing required services to the RFS controller")
Component(rfsModel, "Remote File System Model", "Node.js, Cypher, neo4j-driver", "Consists functions that encapsulates database logic for manipulating the file system tree called by Remote File System services")
Rel(rfsController, rfsService, "Calls")
Rel(rfsService, rfsModel, "Calls")
Rel(rfsService, userService, "Calls")
Rel(rfsService, cloudStorageService, "Calls")

@enduml

